# docker-compose.dev.yml
services:
  stockly-api:
    container_name: stockly-api
    image: stockly-api
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DOTNET_RUNNING_IN_CONTAINER=true
      - Firebase__ProjectId=stockly-db
      - Firebase__CredentialsBase64=${FIREBASE_CREDS_BASE64}  # Injected at runtime
    ports:
      - "5103:5103"
    user: "1000:1000"
    restart: unless-stopped

# No 'secrets:' or volume mounts needed!